apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrapper
  namespace: flux
spec:
  selector:
    matchLabels:
      app: wrapper
  replicas: 1
  template:
    metadata:
      labels:
        app: wrapper
    spec:
      serviceAccountName: helm-wrapper
      containers:
      - name: wrapper
        image: python:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]