---
- hosts: r1
  pre_tasks:
    - name: Make sure eth9 gets IP
      shell: dhclient eth9
  tasks:
    - name: Install BIRD daemon
      package: 
        name: bird
        state: present
        update_cache: true

    - name: Copy BIRD configuration for VNX scenario
      copy:
        src: ../../conf/bird/bird.conf
        dest: /etc/bird/bird.conf

    - name: Restart BIRD daemon to apply configuration
      service:
        name: bird
        state: restarted